name: my_save_app
description: A simpe app to track savings goals.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/launcher_icon.png"
  adaptive_icon_background: "lib/assets/launcher_icon_background.png"
  adaptive_icon_foreground: "lib/assets/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
