name: my_save_app
description: A simpe app to track savings goals.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  adaptive_icon_background: "assets/launcher_icon_background.png"
  adaptive_icon_foreground: "assets/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#FCFEF8"
  image: "assets/launcher_icon.png"

  android_12:
    image: "assets/launcher_icon.png"
    icon_background_color: "#FCFEF8"


flutter:
  uses-material-design: true
  assets:
    - assets/app_bar_icon.png
  generate: true
